# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Home Left Right
  description: Home Left Right block
  icon: 'cottage'
  tags: ['left-right']

# Defines the structure of this component, as well as the default values
blueprint:
  bg_image:
  heading:
  text:
  button: bookshop:global/button
  image:
  image_alt:

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
  text:
    type: markdown
