# Metadata about this component, to be used in the CMS
spec:
  structures:
    - content_blocks
  label: Shared Background Block
  description: Shared Background Block
  icon: 'cottage'
  tags: ['hero']

# Defines the structure of this component, as well as the default values
blueprint:
  background_image:
  hero: bookshop:home/hero
  left_right_blocks: [bookshop:home/left-right]

# Overrides any fields in the blueprint when viewing this component in the component browser
preview:

# Any extra CloudCannon inputs configuration to apply to the blueprint
_inputs:
